spring: 
   security:
      oauth2:
        client:
          registration:
            google:
              clientId: "{YOUR_GOOGLE_CLIENT_ID}"
              clientSecret: "{YOUR_GOOGLE_CLIENT_SECRET}"
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile