spring: 
   security:
      oauth2:
        client:
          registration:
            google:
              clientId: 748377842116-allmtjcvgb6jg380r6p25ik1ib0dqane.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
   mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: 8080
crypto: 
  secret: "jaassecret"
database: 
  username: "root"
  password: "root"
  url: "jdbc:mysql://localhost:3306/springboot"
  driver: "com.mysql.cj.jdbc.Driver"
 